### ISSUE TITLE
Add file or folder creation state to snapshots

### ISSUE THREAD

**Issue by wout** [mdwagner/lucky_template#2]
I'm using a snapshot to report changes to the user. At the moment it looks like this:

```bash
→ Looks like the first time, building the lucky_vite binary...
→ Done building bin/lucky_vite.
✓ config
✓ config/lucky_vite.json
✓ vite.config.js
✓ src
✓ src/js
✓ src/js/entry
✓ src/js/entry/main.js
✓ src/css
✓ src/css/main.css
→ Done setting up files.
```

It would be nice to either have a `.new_item?` method on files and folders (as in, it was created by this action), or a `.status` method returning an enum value (e.g. `Status::Created`/`Status::Existed`). That way, reports created from snapshots can be more detailed.

**Comment by mdwagner** [comment]
When you say you're using a snapshot to report changes, do you mean after you've written it to disk? As in, taken a snapshot of the folder returned by `#write!`? Because that snapshot isn't any different than if you took a snapshot before you wrote it to disk.

Snapshots are meant to be static information about the contents of the folder, regardless of whether it was written to disk or not. When you call `#write!`, it doesn't skip files that are already created, it _always_ writes to them (using File mode "w"). The only reason you might know that a file was changed is by looking at a diff.

My suggestion:
- take a snapshot of the folder _before_ you write it to disk
- use it to look up what files will be created/already existed (keep in mind the content of the file might change)
- write the folder to disk
- output the collected file state information from before the run

**Comment by wout** [comment]
> take a snapshot of the directory before you write it to disk

Great suggestion, thanks!

**Comment by mdwagner** [comment]
Thinking about it more, if I did add a feature like this, it would need to be a different write method that essentially returns the status of the operation. I'm not against adding that, but it is more work than just using the above suggested solution.

**Comment by wout** [comment]
I think your solution is perfect. No need for changes if they aren't necessary.
